//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int senderID { get; set; }
        public int recipientID { get; set; }
        public System.DateTime date { get; set; }
        public string messageContent { get; set; }
        public bool isRead { get; set; }
        public Nullable<System.DateTime> readDate { get; set; }
    }
}
